In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys

In [2]:
os.getcwd()

'/home/hdap/Documents/maestria_unir/practicas/data_david/demografica'

In [3]:
leer = False

In [4]:
if leer:
    archivos_leer = [f for f in os.listdir('./') if 'DEMO_' in f]
    archivos = [pd.read_sas(f, format='xport', encoding='utf-8') for f in archivos_leer]
    registros= np.array([(f.shape[0], f.shape[1]) for f in archivos])
    total_registros = registros.sum(axis = 0)[0]
    pd_demo_total = pd.concat(archivos, axis = 0)
    pd_demo_total.to_csv('SEQN.csv', header = True, sep = '|', index = False)

In [5]:
pd_demo = pd.read_csv('./consolidado_demo.csv', sep = '|')
pd_demo['SEQN'] = pd_demo['SEQN'].astype(int)
pd_demo.shape

(101316, 174)

In [6]:
pd_demo.SEQN.value_counts().min(), pd_demo.SEQN.value_counts().max()

(1, 1)

In [7]:
threshold = [60, 70, 80]

[sum(np.where(pd_demo['RIDAGEYR'] >= thr, 1, 0)) for thr in threshold]

[19087, 10207, 4257]

In [6]:
pd_demo

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGY,...,WTIREP50,WTIREP51,WTIREP52,DMDHRAGZ,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,AIALANG,DMDBORN2,DMDHRBR2
0,62161,7.0,2.0,1.0,2.200000e+01,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62162,7.0,2.0,2.0,3.000000e+00,NaN,1.0,1.0,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62163,7.0,2.0,1.0,1.400000e+01,NaN,5.0,6.0,2.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,62164,7.0,2.0,2.0,4.400000e+01,NaN,3.0,3.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62165,7.0,2.0,2.0,1.400000e+01,NaN,4.0,4.0,2.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101311,21000,2.0,2.0,2.0,1.000000e+01,126.0,3.0,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101312,21001,2.0,2.0,1.0,5.397605e-79,8.0,3.0,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101313,21002,2.0,2.0,1.0,1.000000e+01,120.0,5.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101314,21003,2.0,2.0,1.0,9.000000e+00,116.0,4.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101315,21004,2.0,2.0,1.0,3.100000e+01,372.0,2.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN