In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import traceback

In [17]:
leer = True

          SEQN  enfermedad_diabetes
0      93703.0                  1.0
1      93704.0                  1.0
2      93705.0                  1.0
3      93706.0                  1.0
4      93707.0                  1.0
...        ...                  ...
8892  102952.0                  1.0
8893  102953.0                  1.0
8894  102954.0                  1.0
8895  102955.0                  1.0
8896  102956.0                  1.0

[8897 rows x 2 columns]

In [26]:

if leer:
    anos = ['2003-2004', '2005-2006', '2007-2008', '2009-2010', '2011-2012', '2013-2014','2015-2016', '2017-2018']
    
    extension = ['DIQ_C','DIQ_D','DIQ_E','DIQ_F','DIQ_G','DIQ_H','DIQ_I','DIQ_J','DIQ_K']
    
    archivos = []
    
    for f,j in zip(anos,extension):
        try:
            print(f)
            print('-----------------------------')
            path = 'https://wwwn.cdc.gov/Nchs/Nhanes/{}/{}.XPT'.format(f, j)
            print(path)
            archivo = pd.read_sas(path, format='xport', encoding='utf-8')
            
            if f in ['2003-2004']:
                archivo = archivo[(archivo.DIQ010==1)|(archivo.DIQ050==1)|(archivo.DIQ070==1)|(archivo.DIQ080==1)|(archivo.DIQ090==1)|(archivo.DIQ100==1)|(archivo.DIQ120==1)|(archivo.DIQ140==1)]
            elif f in ['2005-2006', '2007-2008']:
                archivo = archivo[(archivo.DIQ010==1)|(archivo.DIQ160==1)|(archivo.DIQ050==1)|(archivo.DIQ240==1)|(archivo.DIQ080==1)]
            else: 
                archivo = archivo[(archivo.DIQ010==1)|(archivo.DIQ160==1)|(archivo.DIQ050==1)|(archivo.DIQ070==1)|(archivo.DIQ240==1)|(archivo.DIQ080==1)] 
            print(archivo.shape)
            archivo = archivo[['SEQN']]
            archivo[['enfermedad_diabetes']] = 1
            archivos.append(archivo)
        except Exception as exc:
            print(path)
            print(traceback.format_exc())
            print(exc)
            print('--------------------')
            pass
    
    pd_ = pd.concat(archivos, sort='False', ignore_index='True')
    pd_ = pd_.drop_duplicates()
    pd_.to_csv('./total_diabetes.csv', header = True, sep = '|', index = False)
    print(pd_.shape)

2003-2004
-----------------------------
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/DIQ_C.XPT
(1763, 17)
2005-2006
-----------------------------
https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/DIQ_D.XPT
(711, 36)
2007-2008
-----------------------------
https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/DIQ_E.XPT
(1024, 36)
2009-2010
-----------------------------
https://wwwn.cdc.gov/Nchs/Nhanes/2009-2010/DIQ_F.XPT
(1027, 20)
2011-2012
-----------------------------
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/DIQ_G.XPT
(978, 53)
2013-2014
-----------------------------
https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/DIQ_H.XPT
(1040, 54)
2015-2016
-----------------------------
https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DIQ_I.XPT
(1404, 54)
2017-2018
-----------------------------
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DIQ_J.XPT
(1524, 54)
(9471, 2)